### ISSUE TITLE
bitbake fails to apply the patch "0001-Yocto-load-u-boot.img-from-RAW-instead-of-1st-FAT.patch"

### ISSUE THREAD

**Issue by joiie** [TechNexion/u-boot-edm#2]
bitbake fails to apply thc patch 0001-Yocto-load-u-boot.img-from-RAW-instead-of-1st-FAT.patch"
Here is the error log. 
[log.do_patch.17581.txt](https://github.com/TechNexion/u-boot-edm/files/385426/log.do_patch.17581.txt)

Please let me know if you need anything else or if i can do anything to help you.
Here is the logfile of the build as well.
[20160727061149.log.txt](https://github.com/TechNexion/u-boot-edm/files/385430/20160727061149.log.txt)

**Comment by richard-hu** [comment]
Hello, joiie:

I already update the patch '0001-Yocto-load-u-boot.img-from-RAW-instead-of-1st-FAT.patch' to fix this issue.
Could you help me update the Yocto source code and try it again?

I'm sorry to have wasted your time.

BR,

Richard

**Comment by joiie** [comment]
Hello richard-hu:
I tried that branch and got the followig error:
`Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4 CROSS_COMPILE=arm-poky-linux-gnueabi- CC=arm-poky-linux-gnueabi-gcc  --sysroot=/home/hatter/edm-yocto/buildv1/tmp/sysroots/edm-fairy-imx6 edm-cf-imx6_defconfig
|   HOSTCC  scripts/basic/fixdep
| /bin/sh: 1: cc: not found
| scripts/Makefile.host:91: recipe for target 'scripts/basic/fixdep' failed
| make[1]: *** [scripts/basic/fixdep] Error 127
| Makefile:395: recipe for target 'scripts_basic' failed
| make: *** [scripts_basic] Error 2
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/hatter/edm-yocto/buildv1/tmp/work/edm_fairy_imx6-poky-linux-gnueabi/u-boot-edm/2015.04-r0/temp/log.do_compile.27173)`

I will probably reinstall my build machine tomorrow with ubuntu14.4 LTS and try it again
Here are the log files of the build:
[20160727141216.log.txt](https://github.com/TechNexion/u-boot-edm/files/386857/20160727141216.log.txt)
[log.do_compile.27173.txt](https://github.com/TechNexion/u-boot-edm/files/386865/log.do_compile.27173.txt)

**Comment by richard-hu** [comment]
Hello, Joiie:

It seems your ubuntu lacks of some library depended by  gcc.

Please try to install "build-essential":
`sudo apt-get install build-essential 
`
Besides, if your environment is 64-bit ubuntu, you need to install ia32-lib to be compatible with 32-bit library:

Check if your ubuntu is 64-bit:
 `$uname -a`
`Linux ubuntu 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

I uses ubuntu 14.04 64-bit and I need to install ia-32 compatible library as follows:
'sudo apt-get install lib32stdc++6 lib32z1 lib32ncurses5 lib32bz2-1.0 gcc-multilib'

Thank You~!

BR,

Richard

**Comment by joiie** [comment]
Hello richard-hu:
I Just managed to compile and deploy my first image.
Thank you for all your help with this!

i had buld-essential installed but nnot the rest of the 32-bit packages, everything installed fine except lib32bz2-1.0 that have been replaced by libbz2-1.0 ( libbz2-1.0:i386 for the 32 bit version)

**Comment by richard-hu** [comment]
Hello, Joiie:

It's great that yocto 1.7 can also be built under ubuntu 16.04 64bit !!!
Thanks for your feedback and help us improve the software quality.

Thank You ~!!!

BR,

Richard
